version: '3'

services:
  app:
    image: 'docker-booking:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.2-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=booking
      - POSTGRES_PASSWORD=booking
    ports:
      - "5432:5432"
